$(document).ready(function(){
    $('#preson_data').click(function(){
        $('.mem_data_right_div').css('display','flex');
        $('.order_detail_wrap').css('display','none');
        $('.curisine_wrap').css('display','none');
    })
    $('#order_record').click(function(){
        $('.mem_data_right_div').css('display','none');
        $('.order_detail_wrap').css('display','block');
        $('.curisine_wrap').css('display','none');
    })
    $('#customized_curisine').click(function(){
        $('.mem_data_right_div').css('display','none');
        $('.order_detail_wrap').css('display','none');
        $('.curisine_wrap').css('display','block');
    })
})
$(function(){
    $('.order_history_btn').click(function(){
        $('.order_detail_div_wrap').slideToggle(600);
    });
});